name: and_os
description: A Flutter plugin for implementing security checks on Android and iOS devices, including root detection, debugging checks, and tampering prevention.
version: 1.0.0
homepage: https://github.com/Clothless/AndOS
repository: https://github.com/Clothless/AndOS
issue_tracker: https://github.com/Clothless/AndOS/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.clothless.andos.and_os
        pluginClass: AndOsPlugin
      ios:
        pluginClass: AndOsPlugin